"""
Django settings for the Dojo Platform project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
from email.policy import default
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY", default="", cast=str)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=0, cast=bool)
ALLOW_ADMIN = config("ALLOW_ADMIN", default=0, cast=bool)
ALLOWED_HOSTS = config("DJANGO_ALLOWED_HOSTS", default="", cast=str).split()
if not DEBUG:
    CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=str).split()
else:
    CSRF_TRUSTED_ORIGINS = [
        'https://localhost',
        'https://127.0.0.1',
        'https://192.168.3.70',
        'https://*.ngrok-free.app',
        'https://staging.seishinjkadojo.com.co',
    ]

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
# GDAL_LIBRARY_PATH = '/usr/lib/libgdal.so'
# Close session when the browser is closed
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# Set session timeout to 30 minutes (1800 seconds)
SESSION_COOKIE_AGE = 1800
# CSRF_COOKIE_SAMESITE = 'Lax'  # Configuración recomendada para CSRF en producción
# SESSION_COOKIE_SECURE = True  # Solo en producción con HTTPS
# SESSION_COOKIE_SAMESITE = 'Lax'  # Configuración recomendada para sesiones
# CSRF_COOKIE_HTTPONLY = True  # Evita el acceso a la cookie CSRF desde JavaScript
# CSRF_COOKIE_SECURE = True  # Solo en producción con HTTPS
# CSRF_COOKIE_NAME = 'csrftoken'  # Nombre de la cookie CSRF
# CSRF_USE_SESSIONS = True  # Utiliza sesiones para almacenar el token CSRF
# CSRF_COOKIE_PATH = '/'  # Ruta de la cookie CSRF


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user_management',
    'dashboard',
    'test'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Language detection middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'dojo.middlewares.ClearMessagesIfLoggedOutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dojo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.template.context_processors.static',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'dojo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    "default": {
        "ENGINE": config("DOJO_ENGINE", default="django.db.backends.sqlite3", cast=str),
        "NAME": config("DOJO_DB_NAME", default=BASE_DIR / "db.sqlite3", cast=str),
        "USER": config("DOJO_DB_USER", default="user", cast=str),
        "PASSWORD": config("DOJO_DB_PASS", default="password", cast=str),
        "HOST": config("DOJO_DB_HOST", default="localhost", cast=str),
        "PORT": config("DOJO_DB_PORT", default=5432, cast=int),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'user_management.User'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en'  # Cambiar de 'en-us' a 'en' para consistencia

# Supported languages
LANGUAGES = [
    ('en', 'English'),
    ('es', 'Español'),
    ('ja', '日本語'),
]

# Directory for translation files
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'America/Bogota'

USE_I18N = True
USE_L10N = True  # Enable localized formatting
USE_TZ = True

# Language cookie settings
LANGUAGE_COOKIE_NAME = 'django_language'
LANGUAGE_COOKIE_AGE = 31536000  # 1 year (in seconds)
LANGUAGE_COOKIE_PATH = '/'
LANGUAGE_COOKIE_HTTPONLY = False  # Allow JS access for language switcher
LANGUAGE_COOKIE_SAMESITE = 'Lax'


# Email settings for Gmail
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = config("DOJO_EMAIL_HOST", default="smtp.gmail.com", cast=str)
EMAIL_PORT = config("DOJO_EMAIL_PORT", default=587, cast=int)
EMAIL_USE_TLS = config("DOJO_EMAIL_USE_TLS", default=1, cast=bool)
EMAIL_HOST_USER = config("DOJO_EMAIL_HOST_USER", default="jarh1992@gmail.com", cast=str)
EMAIL_HOST_PASSWORD = config("DOJO_EMAIL_HOST_PASSWORD", default="", cast=str)  # NOT your normal password
# Optional, to identify sender
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)
# ------------------------------------- LOGGING ---------------------------------------
logging_level = "DEBUG" if DEBUG else "INFO"
logging_path = BASE_DIR / "logs"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'},
        'require_debug_true': {'()': 'django.utils.log.RequireDebugTrue'},
    },
    'formatters': {
        'main_formatter': {
            'format': '[%(asctime)s] {%(filename)s:%(lineno)d} '
                      '%(levelname)s:%(name)s %(message)s ',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        }
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'main_formatter',
        },
        'production_file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': logging_path / 'main.log',
            'when': 'D',
            'backupCount': 0,
            'formatter': 'main_formatter',
            'filters': ['require_debug_false'],
        },
        'debug_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': logging_path / 'main_debug.log',
            'maxBytes': 1024 * 1024 * 5,
            'backupCount': 7,
            'formatter': 'main_formatter',
            'filters': ['require_debug_true'],
        }
    },
    'loggers': {
        'django.request': {
            'level': 'ERROR',
            'handlers': ['console'],
            'propagate': True,
        },
        'django.db.backends': {
            'level': 'ERROR',
            'handlers': ['console', 'debug_file'],
            'propagate': False,
        },
        'django': {
            'level': logging_level,
            'handlers': ['console', 'debug_file', 'production_file'],
        },
        'application': {
            'level': logging_level,
            'handlers': ['console', 'debug_file', 'production_file'],
        }
    }
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
