services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${DOJO_DB_NAME}
      POSTGRES_USER: ${DOJO_DB_USER}
      POSTGRES_PASSWORD: ${DOJO_DB_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DOJO_DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /app/dojo
    tty: true
    entrypoint: ["/entrypoint.sh"]
    volumes:
      - .:/app
      - ./dojo/static/:/app/static/
      - ./dojo/media/:/app/media/
      - ./dojo/logs:/app/dojo/logs
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal

  nginx:
    image: nginx:1.29
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dojo/static/:/app/static/
      - ./dojo/media/:/app/media/
      - ./certs:/etc/ssl/certs
    depends_on:
      - web
    networks:
      - internal

networks:
  internal:
    driver: bridge

volumes:
  pgdata:
