services:
  db:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/dojo
    tty: true
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/app
      - ./dojo/static/:/app/static/
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Expone el puerto 443 para HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./dojo/static/:/app/static/
    depends_on:
      - web
volumes:
  pgdata:
