services:
  db_local:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: ${DOJO_DB_NAME}
      POSTGRES_USER: ${DOJO_DB_USER}
      POSTGRES_PASSWORD: ${DOJO_DB_PASS}
    volumes:
      - pgdata_local:/var/lib/postgres/data
    ports:
      - "5432:5432"
    env_file:
      - .env_local

  web_local:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.local
    working_dir: /app/dojo
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - ./dojo/static/:/app/static/
      - ./dojo/media/:/app/media/
      - ./dojo/logs:/app/dojo/logs
    ports:
      - "8000:8000"
    env_file:
      - .env_local
    depends_on:
      - db_local
volumes:
  pgdata_local:
