services:
  db:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/dojo
    tty: true
    entrypoint: ["./entrypoint.sh"]
    volumes:
      - .:/app
      - ./dojo/static/:/app/static/
      - ./dojo/logs:/app/dojo/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
volumes:
  pgdata:
