services:
  db_local:
    restart: always
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata_local:/var/lib/postgres/data
    ports:
      - "5431:5431"
  web_local:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.local
    working_dir: /app/dojo
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - ./dojo/static/:/app/static/
      - ./dojo/logs:/app/dojo/logs
    ports:
      - "8000:8000"
    env_file:
      - .env_local
    depends_on:
      - db_local
volumes:
  pgdata_local:
