# Generated by Django 5.2.4 on 2025-09-26 02:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('embusen_diagram', models.ImageField(blank=True, null=True, upload_to='embusen/')),
                ('video_reference', models.URLField(blank=True, null=True)),
                ('order', models.CharField(max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kumite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50)),
                ('video_reference', models.URLField(blank=True, null=True)),
                ('order', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, default='techniques/default_technique.jpg', null=True, upload_to='techniques/')),
                ('type', models.CharField(choices=[('CA', 'Joint Warm-Up'), ('ES', 'Stretching'), ('KI', 'Kihon'), ('KA', 'Kata'), ('KU', 'Kumite')], default='KI', max_length=2)),
                ('level', models.CharField(blank=True, choices=[('PR', 'Beginner'), ('IN', 'Intermediate'), ('AV', 'Advanced')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('description', models.TextField()),
                ('dojo_location', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('email', models.EmailField(default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensei', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensei', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(blank=True, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KataLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('objectives', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='dashboard.kata')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='KataLessonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.katalesson')),
            ],
        ),
        migrations.CreateModel(
            name='KataLessonActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/images/')),
                ('caption', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.katalessonactivity')),
            ],
        ),
        migrations.CreateModel(
            name='KataLessonActivityVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.katalessonactivity')),
            ],
        ),
        migrations.CreateModel(
            name='KataSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='series/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('katas', models.ManyToManyField(related_name='series', to='dashboard.kata')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.CharField(choices=[('KATA', 'Kata'), ('KUMITE', 'Kumite'), ('TECH', 'Technique'), ('PHYS', 'Physical Preparation'), ('MIXED', 'Mixed')], default='MIXED', max_length=10)),
                ('status', models.CharField(choices=[('S', 'Scheduled'), ('O', 'On Going'), ('F', 'Finished'), ('C', 'Canceled')], default='S', max_length=2)),
                ('details', models.TextField(blank=True, help_text='Comentarios o detalles adicionales.', null=True)),
                ('location', models.CharField(default='', max_length=100)),
                ('katas', models.ManyToManyField(blank=True, related_name='trainings', to='dashboard.kata')),
                ('kumites', models.ManyToManyField(blank=True, related_name='trainings', to='dashboard.kumite')),
                ('techniques', models.ManyToManyField(blank=True, related_name='trainings', to='dashboard.technique')),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'Late'), ('E', 'Excused')], default='P', max_length=1)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time at which attendance was recorded.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='dashboard.training')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-timestamp'],
                'unique_together': {('training', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TrainingScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], default='MON', max_length=3)),
                ('time', models.TimeField()),
                ('details', models.TextField(blank=True, null=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.training')),
            ],
            options={
                'verbose_name': 'Automatic Training Schedule',
                'verbose_name_plural': 'Automatic Training Schedules',
                'ordering': ['day_of_week', 'time'],
                'unique_together': {('day_of_week', 'time', 'training')},
            },
        ),
    ]
