# Generated by Django 5.0.9 on 2024-11-25 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='start_time',
        ),
        migrations.AddField(
            model_name='training',
            name='attendants',
            field=models.ManyToManyField(related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='techniques',
            field=models.ManyToManyField(related_name='techniques', to='dashboard.technique'),
        ),
        migrations.AlterField(
            model_name='training',
            name='training_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('description', models.TextField()),
                ('sensei', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sensei', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
