# Generated by Django 5.2.4 on 2025-09-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trainingscheduling',
            unique_together={('day_of_week', 'time')},
        ),
        migrations.RemoveField(
            model_name='trainingscheduling',
            name='training',
        ),
    ]
