# Generated by Django 5.2.4 on 2025-11-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_training_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='details',
            field=models.TextField(blank=True, default='', help_text='Comentarios o detalles adicionales.'),
        ),
    ]
