# Generated by Django 5.0.9 on 2024-11-30 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_training_qr_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='training',
            name='training_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
