# Generated by Django 5.2.4 on 2025-11-22 22:21

import json
from django.db import migrations, models


def clean_json_fields(apps, schema_editor):
    """
    Clean and convert objectives and content fields to valid JSON before type conversion.
    Handles cases where fields contain invalid JSON like '-', empty strings, or plain text.
    """
    KataLesson = apps.get_model('dashboard', 'KataLesson')
    db_alias = schema_editor.connection.alias

    for lesson in KataLesson.objects.using(db_alias).all():
        changed = False

        # Clean objectives field
        if lesson.objectives is not None:
            obj_str = str(lesson.objectives).strip()
            # If empty, dash, or not JSON-like, set to empty list
            if not obj_str or obj_str == '-' or not obj_str.startswith('['):
                lesson.objectives = '[]'
                changed = True
        else:
            lesson.objectives = '[]'
            changed = True

        # Clean content field
        if lesson.content is not None:
            content_str = str(lesson.content).strip()
            # If empty, dash, or not JSON-like, set to empty list
            if not content_str or content_str == '-' or not content_str.startswith('['):
                lesson.content = '[]'
                changed = True
        else:
            lesson.content = '[]'
            changed = True

        if changed:
            lesson.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_training_details'),
    ]

    operations = [
        # Step 1: Clean existing data to ensure valid JSON format
        migrations.RunPython(
            clean_json_fields,
            reverse_code=migrations.RunPython.noop,
        ),

        # Step 2: Change field types to JSONField
        migrations.AlterField(
            model_name='katalesson',
            name='content',
            field=models.JSONField(blank=True, default=list, help_text='List of content items'),
        ),
        migrations.AlterField(
            model_name='katalesson',
            name='objectives',
            field=models.JSONField(default=list, help_text='List of lesson objectives'),
        ),
        migrations.AlterField(
            model_name='katalesson',
            name='order',
            field=models.CharField(default='b0', max_length=3),
        ),
    ]
