# Generated by Django 5.2.4 on 2025-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_training_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalesson',
            name='content',
            field=models.JSONField(blank=True, default=list, help_text='List of content items'),
        ),
        migrations.AlterField(
            model_name='katalesson',
            name='objectives',
            field=models.JSONField(default=list, help_text='List of lesson objectives'),
        ),
        migrations.AlterField(
            model_name='katalesson',
            name='order',
            field=models.CharField(default='b0', max_length=3),
        ),
    ]
