# Generated by Django 5.0.9 on 2024-12-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_technique_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='category',
            field=models.CharField(choices=[('CA', 'Calentamiento Articular'), ('ES', 'Estiramiento'), ('KI', 'Kihon'), ('KU', 'Kumite'), ('PR', 'Principiante'), ('I', 'Intermedio'), ('AV', 'Avanzado')], default='KI'),
        ),
    ]
