# Generated by Django 5.2.4 on 2025-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_katalesson_content_alter_katalesson_objectives_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalesson',
            name='order',
            field=models.CharField(default='b0', max_length=10),
        ),
    ]
