# Generated by Django 5.2.4 on 2025-11-22 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_katalesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalessonactivityimage',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='katalessonactivityimage',
            name='caption',
            field=models.JSONField(blank=True, default=list),
        )
    ]
