# Generated by Django 5.2.4 on 2025-11-22 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_katalessonactivityimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalessonactivityimage',
            name='caption',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
