# Generated by Django 5.2.4 on 2025-12-30 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_katalessonactivityimage_caption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='dashboard.katalessonactivity')),
                ('student', models.ForeignKey(limit_choices_to={'category': 'ST'}, on_delete=django.db.models.deletion.CASCADE, related_name='activity_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Completion',
                'verbose_name_plural': 'Activity Completions',
                'ordering': ['-completed_at'],
                'unique_together': {('student', 'activity')},
            },
        ),
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='dashboard.katalesson')),
                ('student', models.ForeignKey(limit_choices_to={'category': 'ST'}, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson Completion',
                'verbose_name_plural': 'Lesson Completions',
                'ordering': ['-completed_at'],
                'unique_together': {('student', 'lesson')},
            },
        ),
    ]
