# Generated by Django 5.0.13 on 2025-03-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_dojo_address_dojo_city_dojo_country_dojo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('A', 'Scheduled'), ('F', 'Estiramiento'), ('C', 'Kihon')], default='A'),
        ),
    ]
