# Generated by Django 6.0.2 on 2026-03-09 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_training_sempai'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text='Duration of the training session.'),
        ),
    ]
