# Generated by Django 6.0.2 on 2026-03-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_training_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dojo/'),
        ),
    ]
