# Generated by Django 5.2.4 on 2025-08-28 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_kata_kataserie_katalesson_kata_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kata',
            name='serie',
        ),
        migrations.AddField(
            model_name='katalesson',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='dashboard.kataserie'),
        ),
        migrations.AlterField(
            model_name='katalesson',
            name='kata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='dashboard.kata'),
        ),
    ]
