# Generated by Django 5.2.4 on 2025-08-29 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_kata_serie_katalesson_serie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalesson',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='katalesson',
            name='serie',
        ),
        migrations.AddField(
            model_name='kata',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='katalesson',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kataserie',
            name='katas',
            field=models.ManyToManyField(related_name='series', to='dashboard.kata'),
        ),
        migrations.AlterField(
            model_name='kata',
            name='level',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='katalesson',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='katalesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='KataLessonActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='activities/images/')),
                ('video', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='dashboard.katalesson')),
            ],
        ),
    ]
