# Generated by Django 6.0.2 on 2026-03-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_dojo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='type',
            field=models.CharField(choices=[('KIHON', 'Kihon'), ('KATA', 'Kata'), ('KUMITE', 'Kumite'), ('PHYS', 'Physical Preparation'), ('MIXED', 'Mixed')], default='MIXED', max_length=10),
        ),
    ]
