# Generated by Django 5.2.4 on 2025-08-29 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_katalesson_activities_remove_katalesson_serie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katalessonactivity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='katalessonactivity',
            name='video',
        ),
        migrations.CreateModel(
            name='KataLessonActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.katalessonactivity')),
            ],
        ),
        migrations.CreateModel(
            name='KataLessonActivityVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='dashboard.katalessonactivity')),
            ],
        ),
    ]
