# Generated by Django 5.2.4 on 2025-08-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_katalessonactivity_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='katalessonactivity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activities/images/'),
        ),
        migrations.AddField(
            model_name='katalessonactivity',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
