# Generated by Django 5.2.4 on 2025-09-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_katalessonactivity_image_katalessonactivity_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kata',
            name='order',
            field=models.CharField(max_length=100),
        ),
    ]
