# Generated by Django 5.2.4 on 2025-09-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_kata_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kata',
            name='order',
            field=models.CharField(max_length=2),
        ),
    ]
