# Generated by Django 5.2.4 on 2025-09-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_kata_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katalessonactivityimage',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='katalessonactivityvideo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
