# Generated by Django 5.2.4 on 2025-10-15 15:43

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_inf_cons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='accept_regulations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='cardio_prob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('SE', 'Sensei'), ('SP', 'Sempai'), ('ST', 'Student')], default='ST'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='date_reactivated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='drug_cons',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='eps',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=0, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('CC', 'Citizenship card'), ('IC', 'Identity Card'), ('AR', 'Alien Registration Card'), ('PA', 'Passport'), ('OT', 'Other')], default='CC'),
        ),
        migrations.AddField(
            model_name='user',
            name='injuries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lost_cons',
            field=models.BooleanField(default=False, verbose_name='lost consciousness'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_cond',
            field=models.CharField(choices=[('CD', 'Cardiac Diseases'), ('AH', 'Arterial Hypertension'), ('D', 'Diabetes'), ('AR', 'Asthma or respiratory problems'), ('ES', 'Epilepsy or Seizures'), ('MP', 'Musculoskeletal Problems (e.g. Sprains, Fractures)'), ('OT', 'Others'), ('NA', 'No aplicable')], default='NA'),
        ),
        migrations.AddField(
            model_name='user',
            name='other_activities',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_cond',
            field=models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Acceptable'), ('I', 'Needs improvement')], default='A'),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_imgs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='sec_recom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('10k', 'Beginner'), ('9k', '9th kyu'), ('8k', '8th kyu'), ('7k', '7th kyu'), ('6k', '6th kyu'), ('5k', '5th kyu'), ('4k', '4th kyu'), ('3k', '3rd kyu'), ('2k', '2nd kyu'), ('1k', '1st kyu'), ('1d', '1st Dan'), ('2d', '2nd Dan'), ('3d', '3rd Dan'), ('4d', '4th Dan'), ('5d', '5th Dan'), ('6d', '6th Dan'), ('7d', '7th Dan'), ('8d', '8th Dan'), ('9d', '9th Dan'), ('10d', '10th Dan')], default='10k'),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('type', models.CharField(choices=[('SU', 'Sign up'), ('PR', 'Password reset'), ('O', 'Other')], default='O', max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
