# Generated by Django 5.0.6 on 2024-07-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='date_reactivated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('10k', 'undefined'), ('9k', '9th kyu'), ('8k', '8th kyu'), ('7k', '7th kyu'), ('6k', '6th kyu'), ('5k', '5th kyu'), ('4k', '4th kyu'), ('3k', '3th kyu'), ('2k', '2th kyu'), ('1k', '1th kyu'), ('1d', '1th Dan'), ('2d', '2th Dan'), ('3d', '3th Dan'), ('4d', '4th Dan'), ('5d', '5th Dan'), ('6d', '6th Dan'), ('7d', '7th Dan'), ('8d', '8th Dan'), ('9d', '9th Dan')], default=('10k', 'undefined')),
        ),
    ]
