# Generated by Django 5.2.4 on 2026-01-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_user_picture_userdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('NA', 'No response')], default='M'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
