# Generated by Django 5.0.6 on 2024-11-11 19:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2000, 1, 1, 0, 0)),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='eps',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='id_number',
            field=models.CharField(default=0, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de extranjería'), ('PA', 'Pasaporte'), ('OT', 'Otro')], default='CC', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('10k', 'Beginner'), ('9k', '9th kyu'), ('8k', '8th kyu'), ('7k', '7th kyu'), ('6k', '6th kyu'), ('5k', '5th kyu'), ('4k', '4th kyu'), ('3k', '3th kyu'), ('2k', '2th kyu'), ('1k', '1th kyu'), ('1d', '1th Dan'), ('2d', '2th Dan'), ('3d', '3th Dan'), ('4d', '4th Dan'), ('5d', '5th Dan'), ('6d', '6th Dan'), ('7d', '7th Dan'), ('8d', '8th Dan'), ('9d', '9th Dan'), ('10d', '10th Dan')], default=('10k', 'Beginner')),
        ),
    ]
