# Generated by Django 5.2.4 on 2026-01-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_user_gender_alter_user_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='medical_cond',
            field=models.CharField(choices=[('CD', 'Cardiac Diseases'), ('AH', 'Arterial Hypertension'), ('D', 'Diabetes'), ('AR', 'Asthma or respiratory problems'), ('ES', 'Epilepsy or Seizures'), ('MP', 'Musculoskeletal Problems (e.g. Sprains, Fractures)'), ('OT', 'Others'), ('NA', 'Not applicable')], default='NA'),
        ),
    ]
