# Generated by Django 5.0.9 on 2024-11-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0005_user_birth_date_user_birth_place_user_eps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accept_inf_cons',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='cardio_prob',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('S', 'Sensei'), ('E', 'Estudiante')], default='E', max_length=1),
        ),
        migrations.AddField(
            model_name='user',
            name='drug_cons',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='injuries',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lost_cons',
            field=models.BooleanField(default=False, verbose_name='lost consciousness'),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_cond',
            field=models.CharField(choices=[('EC', 'Enfermedades Cardiacas'), ('HA', 'Hipertensión Arterial'), ('D', 'Diabetes'), ('AoPR', 'Asma O Problemas Respiratorios'), ('EoC', 'Epilepsia O Convulsiones'), ('PME', 'Problemas Musculoesqueléticos (Ej. Esguinces, Fracturas)'), ('OT', 'Otros'), ('NA', 'No Aplica')], default='NA'),
        ),
        migrations.AddField(
            model_name='user',
            name='other_activities',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_cond',
            field=models.CharField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('A', 'Aceptable'), ('I', 'Necesita mejorar')], default='A'),
        ),
        migrations.AddField(
            model_name='user',
            name='physical_limit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sec_recom',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent',
            field=models.CharField(blank=True, default='', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='parent_phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
