# Generated by Django 6.0.2 on 2026-03-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_user_accept_priv_pol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('CC', 'Citizenship card'), ('IC', 'Identity Card'), ('CR', 'Civil Registration'), ('AR', 'Alien Registration Card'), ('PA', 'Passport'), ('OT', 'Other')], default='CC'),
        ),
    ]
