# Generated by Django 6.0.2 on 2026-03-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_user_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.CharField(choices=[('DI', 'Diploma'), ('CE', 'Certificate'), ('ME', 'Medical Document'), ('ID', 'Identification'), ('PP', 'Payment Proof'), ('OT', 'Other')], default='OT', max_length=2, verbose_name='Document Type'),
        ),
        migrations.AlterField(
            model_name='userdocument',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title'),
        ),
    ]
