# Generated by Django 5.0.9 on 2024-11-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0009_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.TextField(blank=True, default=0, null=True),
        ),
    ]
