# Generated by Django 5.0.9 on 2024-11-29 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0013_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
    ]
