# Generated by Django 5.0.11 on 2025-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0014_remove_token_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('S', 'Sensei'), ('E', 'Student')], default='E', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('CC', 'Citizenship card'), ('TI', 'Identity Card'), ('CE', 'Alien Registration Card'), ('PA', 'Passport'), ('OT', 'Otro')], default='CC', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_cond',
            field=models.CharField(choices=[('EC', 'Cardiac Diseases'), ('HA', 'Arterial Hypertension'), ('D', 'Diabetes'), ('AoPR', 'Asthma and respiratory problems'), ('EoC', 'Epilepsy or Seizures'), ('PME', 'Musculoskeletal Problems (e.g. Sprains, Fractures)'), ('OT', 'Others'), ('NA', 'No aplicable')], default='NA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='physical_cond',
            field=models.CharField(choices=[('E', 'Excellent'), ('B', 'Good'), ('A', 'Acceptable'), ('I', 'Needs improvement')], default='A'),
        ),
    ]
