# Generated by Django 5.0.13 on 2025-03-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0017_alter_user_level_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('SE', 'Sensei'), ('ST', 'Student')], default='ST'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('CC', 'Citizenship card'), ('IC', 'Identity Card'), ('AR', 'Alien Registration Card'), ('PA', 'Passport'), ('OT', 'Otro')], default='CC'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_cond',
            field=models.CharField(choices=[('CD', 'Cardiac Diseases'), ('AH', 'Arterial Hypertension'), ('D', 'Diabetes'), ('AR', 'Asthma and respiratory problems'), ('ES', 'Epilepsy or Seizures'), ('MP', 'Musculoskeletal Problems (e.g. Sprains, Fractures)'), ('OT', 'Others'), ('NA', 'No aplicable')], default='NA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='physical_cond',
            field=models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Acceptable'), ('I', 'Needs improvement')], default='A'),
        ),
    ]
