# Generated by Django 5.2.4 on 2025-08-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0020_user_accept_regulations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('SE', 'Sensei'), ('SP', 'Sempai'), ('ST', 'Student')], default='ST'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_type',
            field=models.CharField(choices=[('CC', 'Citizenship card'), ('IC', 'Identity Card'), ('AR', 'Alien Registration Card'), ('PA', 'Passport'), ('OT', 'Other')], default='CC'),
        ),
    ]
