# Generated by Django 5.2.4 on 2025-08-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0021_alter_user_category_alter_user_id_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('SU', 'Sign up'), ('RG', 'Registration'), ('O', 'Other')], default='O'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medical_cond',
            field=models.CharField(choices=[('CD', 'Cardiac Diseases'), ('AH', 'Arterial Hypertension'), ('D', 'Diabetes'), ('AR', 'Asthma or respiratory problems'), ('ES', 'Epilepsy or Seizures'), ('MP', 'Musculoskeletal Problems (e.g. Sprains, Fractures)'), ('OT', 'Others'), ('NA', 'No aplicable')], default='NA'),
        ),
    ]
