# Generated by Django 5.2.4 on 2025-08-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0023_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('SU', 'Sign up'), ('RG', 'Recover password'), ('O', 'Other')], default='O'),
        ),
    ]
