# Generated by Django 5.2.4 on 2025-08-12 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0024_alter_token_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('SU', 'Sign up'), ('PR', 'Password reset'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
